get http://localhost:5000/login

###

get http://localhost:5000/userdata/dabbiruhaneesh@gmail.com

###

POST  http://localhost:5000/signup
Content-Type: application/json

{
    "name":"haneesh",
    "email":"haneeshtcsguy@gmail.com",
    "password":"randompass",
    "college":"anits",
    "phone":978821778,
    "occupation":"student"

}
###
POST  http://localhost:5000/login
Content-Type: application/json

{
   
    "email":"haneeshtcsguy@gmail.com",
    "password":"randompass"

}

###
POST  http://localhost:5000/addQuiz
Content-Type: application/json

{
   
    "subjectName":"science",
    "description":"science quiz",
    "questions": [{
        "question": "Who discovered Raman effect?",
        "options": [{
            "option":"Ramanujan",
            "isAnswer":false
        },
        {
            "option":"CV Raman",
            "isAnswer":true
        },
        {
            "option":"Plank",
            "isAnswer":false
        },
        {
            "option":"Bohr",
            "isAnswer":false
        }]
    }]

}
### 
get http://localhost:5000/quizzes/mvgr

# ###
# get http://localhost:5000/quizzes/fetch/mvgr/64b80746e35c0412d56d2e2f